ALTER TABLE activations ADD COLUMN IF NOT EXISTS os_name VARCHAR(40) NOT NULL DEFAULT '';
ALTER TABLE activations ADD COLUMN IF NOT EXISTS os_edition VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE activations ADD COLUMN IF NOT EXISTS os_version VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE activations ADD COLUMN IF NOT EXISTS os_build VARCHAR(80) NOT NULL DEFAULT '';
ALTER TABLE activations ADD COLUMN IF NOT EXISTS architecture VARCHAR(30) NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS ix_audit_events_created_id
    ON audit_events(created_at DESC, id DESC);
